# Generated by Django 3.0.7 on 2020-06-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='color',
        ),
        migrations.AddField(
            model_name='card',
            name='context',
            field=models.TextField(default='Debit Card'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(choices=[('Debit Card', 'Debit'), ('Credit Card', 'Credit')], max_length=30),
        ),
    ]
