# Generated by Django 3.0.7 on 2020-06-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20200614_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(choices=[('debit', 'Debitcard'), ('credit', 'Creditcard')], max_length=30),
        ),
    ]
