# Generated by Django 3.0.7 on 2020-06-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20200614_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=30),
        ),
    ]
